-- AlterTable
ALTER TABLE `comments` ADD COLUMN `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    ADD COLUMN `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);

-- AlterTable
ALTER TABLE `requisition` MODIFY `status` ENUM('HISTORY', 'REJECTED', 'DRAFT', 'FORUM', 'CLERK', 'MOVING', 'APPROVED') NOT NULL DEFAULT 'MOVING';
